stats = [
    'force',
    'int',
    'stm',
    'mental',
    'phyatk',
    'mgatk',
    'idatk',
    'attackspd',
    'castspd',
    'movespd',
    'phycrit',
    'mgcrit',
    
    'fire_atk',
    'water_atk',
    'light_atk',
    'dark_atk',
    'fire_resist',
    'water_resist',
    'light_resist',
    'dark_resist',
]